# Generated by Django 3.2.7 on 2022-01-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220103_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='default_mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
