# Generated by Django 3.2.7 on 2021-09-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210918_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='street_address2',
            new_name='charity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street_address1',
            new_name='street_address',
        ),
    ]
