# Generated by Django 3.2.7 on 2021-09-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210919_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='charity',
        ),
    ]
