# Generated by Django 3.2.7 on 2021-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
