# Generated by Django 3.2.7 on 2021-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favorite_charity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='favorite_charity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
