# Generated by Django 3.2.7 on 2021-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20211004_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='favorite_charity',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='favorite_charity',
        ),
        migrations.AddField(
            model_name='order',
            name='charity',
            field=models.CharField(choices=[('Star_forlife', 'Star For Life'), ('Hello', 'Hello'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='Hello', max_length=12),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='charity',
            field=models.CharField(choices=[('Star_forlife', 'Star For Life'), ('Hello', 'Hello'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='Hello', max_length=100),
        ),
    ]
