# Generated by Django 3.2.7 on 2021-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20211005_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charity',
            field=models.CharField(choices=[('Star_for_life', 'Star For Life'), ('Unicef', 'Unicef'), ('Red_Cross', 'Red Cross'), ('Oceana', 'Oceana'), ('Plastic_Ocean_Foundation', 'Plastic Ocean Foundation')], default='Star_For_life', max_length=24),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='charity',
            field=models.CharField(choices=[('Star_for_life', 'Star For Life'), ('Unicef', 'Unicef'), ('Red_Cross', 'Red Cross'), ('Oceana', 'Oceana'), ('Plastic_Ocean_Foundation', 'Plastic Ocean Foundation')], default='Star_For_life', max_length=24),
        ),
    ]
